// Generated by CoffeeScript 2.5.1
(function() {
  /*
  	wheeee
  */
  var array1, bigsum, out, sum;

  sum = function(a, b) {
    return a + b;
  };

  bigsum = function(nums) {
    var result;
    result = 0;
    nums.forEach(function(n) {
      return result += n;
    });
    return result;
  };

  array1 = [3, 1, 4, 1, 5];

  document.write(5);

  out = bigsum(array1);

  document.write(out);

}).call(this);
