// Generated by CoffeeScript 2.5.1
  /*
  	wheeee
  */
  var adddiv, array1, bigsum, check, out, sum;

  sum = function(a, b) {
    return a + b;
  };

  bigsum = function(nums) {
    var result;
    result = 0;
    nums.forEach(function(n) {
      return result += n;
    });
    return result;
  };

  array1 = [3, 1, 4, 1, 5];

  document.write(5);

  out = bigsum(array1);

  document.write(out);

  //input validator:
  adddiv = function(cont) {
    var moo;
    moo = document.createElement("h2");
    moo.textContent = "hi!";
    cont.appendChild(moo);
    return 1;
  };

  check = function() {
	let conta = document.createElement("div");
	div.id = "conta";
	div.innerHTML = "<p>moo hi</p>";
	document.body.appendChild(conta);
    /*var i, inp, ref, text, x;
    inp = document.getElementById("sz").value;
    if (isNaN(inp)) {
      text = "enter an actual number";
    } else if (inp < 1) {
      text = "enter a positive number";
    } else if (inp > 20) {
      text = "smaller input please";
    } else {
      text = "enter lines below";
	  let cont = document.createElement("div");
	  cont.id = "buttonarea";
      for (x = i = 1, ref = inp; (1 <= ref ? i <= ref : i >= ref); x = 1 <= ref ? ++i : --i) {
        addiv(cont);
      }
    }
    document.getElementById("outhere").innerHTML = text;
    return 1;*/
  };

